### ISSUE TITLE
math error handling

### ISSUE THREAD

**Issue by nershman** [nershman/circle-intersection#1]
>>> intersectionArea(218922995834555169026,110000000000000000000)
1.5618595783939063e+37
>>> intersectionArea(218922995834555169026,109000000000000000000)
Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    intersectionArea(218922995834555169026,109000000000000000000)
  File "/Users/sma/Documents/GitHub/circle-intersection/calculate.py", line 9, in intersectionArea
    return float(r*r*(2*math.acos(d/(2*r))-math.sin(2*math.acos(d/(2*r)))))
ValueError: math domain error
>>> intersectionArea(218922995834555169026,10999999999999999999)
Traceback (most recent call last):
  File "<pyshell#22>", line 1, in <module>
    intersectionArea(218922995834555169026,10999999999999999999)
  File "/Users/sma/Documents/GitHub/circle-intersection/calculate.py", line 9, in intersectionArea
    return float(r*r*(2*math.acos(d/(2*r))-math.sin(2*math.acos(d/(2*r)))))
ValueError: math domain error
>>> intersectionArea(218922995834555169026,10909999999999999999)
Traceback (most recent call last):
  File "<pyshell#23>", line 1, in <module>
    intersectionArea(218922995834555169026,10909999999999999999)
  File "/Users/sma/Documents/GitHub/circle-intersection/calculate.py", line 9, in intersectionArea
    return float(r*r*(2*math.acos(d/(2*r))-math.sin(2*math.acos(d/(2*r)))))
ValueError: math domain error

**Comment by nershman** [comment]
left out a 9..


>>> intersectionArea(218922995834555169026,109461497917277590000)
0.0
